# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 7abc9afa7bd306332122339dc9eb9d8d

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc3d562e6dbde7fac7b23ddfc1bf04ffe316f8d7df383da0cb35f848391b8660d1e1e64ac3f35bd9123b1b61f7e21397fffe7f597c6eb70cd25cc28d376a49c1

test:
  secret_key_base: f9d33374e138a096653639c71ad7ba16808d6e7de8ab5d2130dd5d5923c1982bc613f4e9d04bf82fc003d403bac87ff7719f5c8170656f9151b7bcfe1ed907b2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
